
CATEGORIAS_BANDERA = [
    ('BASE', 'BASE'),
    ('NIVEL', 'NIVEL')
]

NIVEL = [
    ('ASOCIADO A', 'ASOCIADO A'),
    ('ASOCIADO B', 'ASOCIADO B'),
    ('ASOCIADO C', 'ASOCIADO C'),
    ('TITULAR A', 'TITULAR A'),
    ('TITULAR B', 'TITULAR B'),
    ('TITULAR C', 'TITULAR C')
]

GPO_LABORAL = [
    ('DOCENTE INVESTIGADOR','DOCENTE INVESTIGADOR'),
    ('ACADÉMICO PROFESIONAL','ACADÉMICO PROFESIONAL'),
    ('TÉCNICO ACADÉMICO','TÉCNICO ACADÉMICO'),
    ('AUXILIAR/DOCENTE','AUXILIAR/DOCENTE')
]
CATEGORIA_COD = [
    ('TIEMPO COMPLETO','TIEMPO COMPLETO'),
    ('MEDIO TIEMPO','MEDIO TIEMPO'),
    ('HORA CLASE','HORA CLASE'),
    ('TIEMPO COMPLETO + HORA CLASE','TIEMPO COMPLETO + HORA CLASE'),
    ('MEDIO TIEMPO + HORA CLASE','MEDIO TIEMPO + HORA CLASE'),
    ('HORA CLASE DE TIEMPO COMPLETO','HORA CLASE DE TIEMPO COMPLETO'),
    ('HORA CLASE DE MEDIO TIEMPO','HORA CLASE DE MEDIO TIEMPO')
]
CATEGORIA_GRADOS = [
    ('BACHILLERATO', 'BACHILLERATO'),
    ('LICENCIATURA', 'LICENCIATURA'),
    ('MAESTRÍA', 'MAESTRÍA'),
    ('DOCTORADO', 'DOCTORADO'),
    ('POSDOCTORADO', 'POSDOCTORADO'),
    ('ESPECIALIDAD', 'ESPECIALIDAD')
]
ESTADO_CIVIL = [
    ('CASADO','CASADO'),
    ('SOLTERO','SOLTERO'),
    ('UNIÓN LIBRE','UNIÓN LIBRE'),
    ('VIUDO','VIUDO'),
    ('DIVORCIADO','DIVORCIADO')
]
SEXO = [
    ('HOMBRE', 'HOMBRE'),
    ('MUJER', 'MUJER')
]
OFICIO = [
    ('COMISION MIXTA', 'COMISION MIXTA'),
    ('RECTOR', 'RECTOR')
]
VIA = [
    ('PUNTOS', 'PUNTOS'),
    ('REQUISITOS', 'REQUISITOS')
]
NIVELES_SNI = [
    ('CANDIDATO', 'CANDIDATO'),
    ('SNI 1', 'SNI 1'),
    ('SNI 2', 'SNI 2'),
    ('SNI 3', 'SNI 3')
]